


nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC01.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc01.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc01.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC02.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc02.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc02.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC03.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc03.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc03.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC04.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc04.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc04.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC05.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc05.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc05.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC06.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc06.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc06.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC07.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc07.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc07.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC08.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc08.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc08.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC09.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc09.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc09.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC10.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc10.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc10.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC11.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc11.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc11.log &
nohup /stornext/General/data/user_managed/grpu_mritchie_1/LuyiTian/sclong_draft/test_p /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/BC12.fastq.gz /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out/bc12.csv > /wehisan/general/user_managed/grpu_naik.s_1/sis_seq_promethion/out.bc12.log &